name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.3.3
  intl_phone_number_input: ^0.7.3
  pin_code_fields: ^8.0.1
  carousel_slider: ^4.2.1
  lottie: ^3.0.0
  audioplayers: ^5.2.1
  just_audio: ^0.9.46
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  table_calendar: ^3.2.0
  get: ^4.7.2
  image_picker: ^1.0.7
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - lib/images/


  
