// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRyf7gXtGUmkOXSUBKKl7ysVDUhwErgf8',
    appId: '1:536166140736:web:930bfb2219b6e21e4548a5',
    messagingSenderId: '536166140736',
    projectId: 'mobile-lms-a8f7b',
    authDomain: 'mobile-lms-a8f7b.firebaseapp.com',
    storageBucket: 'mobile-lms-a8f7b.firebasestorage.app',
    measurementId: 'G-96755JD4FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNdjgrm896yzr9IKULmZffYkrJirXR6z8',
    appId: '1:536166140736:android:82632635f120ff154548a5',
    messagingSenderId: '536166140736',
    projectId: 'mobile-lms-a8f7b',
    storageBucket: 'mobile-lms-a8f7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX_v0TH6a8rwzvkHPTJ-W_dJF0WGPBeSQ',
    appId: '1:536166140736:ios:7372527bbc38acc04548a5',
    messagingSenderId: '536166140736',
    projectId: 'mobile-lms-a8f7b',
    storageBucket: 'mobile-lms-a8f7b.firebasestorage.app',
    iosClientId: '536166140736-mmlkidi5egujqfvj6hsbdke2b6nsip7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX_v0TH6a8rwzvkHPTJ-W_dJF0WGPBeSQ',
    appId: '1:536166140736:ios:7372527bbc38acc04548a5',
    messagingSenderId: '536166140736',
    projectId: 'mobile-lms-a8f7b',
    storageBucket: 'mobile-lms-a8f7b.firebasestorage.app',
    iosClientId: '536166140736-mmlkidi5egujqfvj6hsbdke2b6nsip7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRyf7gXtGUmkOXSUBKKl7ysVDUhwErgf8',
    appId: '1:536166140736:web:318b0e5b2ba135854548a5',
    messagingSenderId: '536166140736',
    projectId: 'mobile-lms-a8f7b',
    authDomain: 'mobile-lms-a8f7b.firebaseapp.com',
    storageBucket: 'mobile-lms-a8f7b.firebasestorage.app',
    measurementId: 'G-XVN6697ZLY',
  );
}
